project:
  type: website
  output-dir: ../docs
website:
  title: Reddit News Analysis
  favicon: favicon.png
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "I. Overview"
        contents:
          # - summary.qmd
          - goals.qmd
          
      - section: "Exploratory Data Analysis"
        contents:
          - eda.qmd
      - section: "III. Natural Language Processing"
        contents:
          - nlp.qmd
      - section: "IV. Machine Learning"
        contents:
          - ml.qmd
      # - section: "V. Results"
      #   contents:
      #     - results.qmd
      #     - appendix.qmd     



format:
  html:
    theme: sandstone
    css: style.css
    toc: true
    toc-depth: 3
    toc-location: right 
    toc-title: "Webpage Contents"
    toc-expand: true

