# Business Goals 
## Exploratory Data Analysis Goals 
<div class = "goals_format"> 
<b> <a href = "eda.qmd#EDA1_DailyEngagement" class = "eda_goal_link"> Business Goal -1 :</a></b> Determine which day people use Reddit most frequently.<br> 
<div class = "tech_format">
<b> Technical proposal: </b> To find this, we will extract the day from the DateTime variable. We will then group by the new day variable and count the group by data. We will create a bar graph of the counts to visualize the findings. This will be conducted for both comments and submissions.</div> </div>
<br> 
<br>

<div class = "goals_format">
<b> <a href = "eda.qmd#EDA2_DifferencePosts" class = "eda_goal_link">Business Goal - 2 :</a></b> Determine the frequency of fake news identifiers.<br>
<div class = "tech_format">
<b>Technical proposal :</b> We will extract the year from the DateTime variable. Using this, we will group by year and count the grouped data. We will visualize our findings in a table that includes comments and submissions. </div> </div> 
<br>
<br>
<div class = "goals_format">
<b> <a href = "eda.qmd#EDA3_FakeNews" class = "eda_goal_link">Business Goal - 3 :</a></b> Determine which fake news identifier is used the most.
<br> 
<div class = "tech_format">
<b>Technical Proposal :</b> First, we will utilize regex to match on different fake news identifiers like bullshit, propaganda, or fake news. Using this, we will create a fake news indicator column that shows if the phrase was present in the comment. Then, we will group by the indicator column and count the groups. We will visualize our findings in a table.</div> </div>
<br> 
<br>
<div class = "goals_format">
<b><a href = "eda.qmd#EDA4: Active Users" class = "eda_goal_link">Business Goal - 4 :</a></b> Who are those most active accounts in these news subreddits?
<br>
<div class = "tech_format">
<b>Technical Proposal :</b> To determine the most active accounts in the news subreddits, we will identify the top 10 users with the highest number of posts. We will extract the usernames from the dataset and group by each user to count their posts. Then, we will compare the number of posts made by these top users in both subreddits. Finally, we will present the findings in a bar chart.</div></div> 
<br>
<br>
<div class = "goals_format">
<b><a href = "eda.qmd#EDA5: News Sources" class = "eda_goal_link">Business Goal - 5 :</a></b> Determine the frequency and the accumulated scores of news sources.
<br>
<div class = "tech_format">
<b>Technical Proposal: </b> In this analysis, our objective is to comprehend the frequency and cumulative scores associated with different news sources. Initially, we'll extract the "domain" information from the URL of each post. Subsequently, we'll aggregate the data based on these sources, computing both the frequency of posts and summarizing the scores attributed to each source. </div></div> 
<br>
<br>

## Natural Language Processing Goals 
<div class = "nlp_goals_format">
<b><a href = "" class = "nlp_goal_link">Business Goal - 6 :</a></b> Determine the news topics that are interacted with the most.
<br><!--<b><a href = "nlp.qmd#topic_modeling" class = "nlp_goal_link">Business Goal - 6 :</a></b> -->
Among all types of news, which category do people concern about the most? Is it related to war, disaster,  food crisis or something else?
<br>
<div class = "nlp_tech_format">
<b>Technical Proposal:</b> Use topic modeling to create different broad news categories. Group by those categories and analyze the comments.</div></div>
<br>
<br>

<div class = "nlp_goals_format">
<b><a href = "" class = "nlp_goal_link">Business Goal - 7 :</a></b> 
<!--<b><a href = "nlp.qmd#ner" class = "nlp_goal_link">Business Goal - 7 :</a></b>  -->
Determine what topics are perceived as fake news.
<br>
<div class = "nlp_tech_format">
<b>Technical Proposal :</b> Use topic modeling created above. Perform sentiment analysis on the comments. Comments with negative sentiment and containing misinformation identifiers will be misinformation. Topics with more of these comments will be perceived as fake news. 
</div></div>
<br>
<br>


<div class = "nlp_goals_format">
<b><a href = "" class = "nlp_goal_link">Business Goal - 8 :</a></b>
<!--<b><a href = "nlp.qmd#sentiment" class = "nlp_goal_link">Business Goal - 8 :</a></b> -->
Find this difference in perceived misinformation from 2021 (post-election year) to 2023 (pre-election year).
<br>
<div class = "nlp_tech_format">
<b>Technical Proposal :</b> We will use the combined sentiment analysis and misinformation indicator to identify comments with negative sentiment and contain a misinformation indicator. We will group by this new variable and count the grouped data. Since there are significantly fewer comments in 2023, we will then take the rate of misinformation comments to compare the two.</div></div> 
<br>
<br> 

## Machine Learning Goals 

<div class = "ml_goals_format">
<b><a href = "" class = "ml_goal_link">Business Goal - 8 :</a></b>
<!--<b><a href = "ml.qmd#super_sentiment" class = "ml_goal_link">Business Goal - 9 :</a></b> -->
Which articles might be perceived as misinformation, or labeled by users as fake news?
<br>
<div class = "ml_tech_format">
<b>Technical Proposal :</b> We employ a supervised machine learning model to predict articles that are prone to be perceived as misinformation. Specifically, we'll utilize techniques such as logistic regression to add precision and robustness to the classification process. By analyzing various attributes of article titles, we'll identify patterns that indicate potential fake news. This comprehensive approach will not only highlight the types of titles more likely to be labeled as fake news but also pinpoint the key features crucial for classification accuracy. This will enhance our understanding of misinformation dynamics and improve our ability to detect and mitigate its spread. </div> </div> 
<br>
<br>

<div class = "ml_goals_format">
<b><a href = "" class = "ml_goal_link">Business Goal - 9 :</a></b>
<!--<b><a href = "ml.qmd#super_sentiment" class = "ml_goal_link">Business Goal - 9 :</a></b> -->
During a public health emergency like COVID-19, how does it impact people's activity on the New and WorldNews subreddits?
<br>
<div class = "ml_tech_format">
<b>Technical Proposal :</b> Our team aims to quantitatively assess how these events have influenced user activity on the News and WorldNews subreddits. We plan to employ linear regression and correlation analysis techniques to explore relationships between COVID-19 case data and the volume of comments, particularly those identified as misinformation. By integrating comprehensive COVID-19 statistics with misinformation comment counts, we intend to uncover patterns that may reveal shifts in user engagement and misinformation dissemination during key phases of the pandemic. This analysis will not only provide a clearer understanding of the pandemic's effect on information exchange in these forums but also help identify misinformation trends that could inform future public health communication strategies. </div> </div> 
<br>
<br>

<div class = "ml_goals_format">
<b><a href = "ml.qmd#controversiality" class = "ml_goal_link">Business Goal - 10 :</a></b> 
<!--<b><a href = "ml.qmd#controversiality" class = "ml_goal_link">Business Goal - 10 :</a></b> -->
Among political topics, is there any correlation? Are certain topics mentioned together more frequently than others?<br>
<div class = "ml_tech_format">
<b>Technical Proposal :</b> We will employ K-means clustering to analyze relationships between different political topics. After conducting topic modeling, we will filter out topics irrelevant to politics, ensuring our focus remains on pertinent themes. This analysis aims to uncover the connections and interactions among various political themes, providing insights into how these topics coalesce and influence public discourse. Understanding these relationships will offer valuable context for policymakers and analysts seeking to interpret trends and patterns within political discussions.</div></div>
<br>
<br> 


## Future Goals
<div class = "future_goals_format">
<b><a href = "ml.qmd#future_analysis" class = "future_goal_link">Business Goal - 11 :</a></b> Among political topics, is there any correlation? Are certain topics mentioned together more frequently than others?
<div class = "future_tech_format">
<b>Technical Proposal:</b> We will conduct a network analysis to explore the relationships between different political topics. This analysis will help us understand the connections and interactions among various political themes, providing insights into how they are interconnected or influence each other within the broader political landscape. </div></div> 


